### ISSUE TITLE
`Logger` is undefined

### ISSUE THREAD

**Issue by nikolaev-dm** [inhere/go-web-skeleton#2]
https://github.com/inhere/go-web-skeleton/blob/16134e80ece1bd335df421bd20ae03fab2290b60/app/boot.go#L128

After the build project I get an error from the compiler

> app/boot.go:128:62: undefined: Logger

**Comment by nikolaev-dm** [comment]
https://github.com/inhere/go-web-skeleton/blob/16134e80ece1bd335df421bd20ae03fab2290b60/app/signal_listen.go#L35

and here too.

**Comment by inhere** [comment]
😄 Thanks for your reminder, I will fix them.

**Comment by inhere** [comment]
hi @johnny-silverhand 

all error has been fixed.

**Comment by nikolaev-dm** [comment]
Hi @inhere. Thanks for the reply. I appreciate you not abandoning the project. :innocent:
